'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class search_property_advance

    '''<summary>
    '''Label_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadioButtonList_transaction_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList_transaction_type As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''SqlDataSource_transactiontype1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_transactiontype1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DropDownList_property_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_property_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSource_propertytype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_propertytype As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DropDownList_state control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_state As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSource_state control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_state As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DropDownList_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_city As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSource_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_city As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DropDownList_budget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_budget As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSource_budget1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_budget1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DropDownList_no_of_bedrooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_no_of_bedrooms As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TextBox_max_area control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_max_area As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox_price_per_sqft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_price_per_sqft As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_search As Global.System.Web.UI.WebControls.Button
End Class
